---
title: "Seminar pri predmetu Načrtovanje kliničnih in epidemioloških raziskav"
subtitle: "A 28- Day Ecological Momentary Assessment of Mental Health Among Psychiatric Outpatients With Suicidal Ideation"
author: "Neža Kržan, Tom Rupnik"
output:
  pdf_document:
    fig_caption: true
    number_sections: true
header-includes:
- \usepackage[slovene]{babel}
- \usepackage{float}
- \usepackage[T1]{fontenc}
- \usepackage{longtable}
- \usepackage{booktabs}
- \usepackage{array}
- \usepackage{makecell}
- \renewcommand\cellalign{lt}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "center",
	fig.pos = "H",
	message = FALSE,
	warning = FALSE,
	results = F, fig.height = 4, fig.width = 5
)

set.seed(2024)
```

# Raziskovalno vprašanje

Ker je samomor izziv javnega zdravstva v Južni Koreji, so analizirali 28-dnevni vzorec samomorilnih misli pri psihiatričnih bolnikih z različnim tveganjem za samomor. Glavna vprašanja so bila: opis demografskih in duševnih značilnosti, primerjava vzorcev samomorilnih misli med visokorizičnimi in nizkorizičnimi skupinami ter ugotovitev povezav med samomorilnim razmišljanjem, depresijo, anksioznostjo in stresom skozi čas z metodo EMA.

Prevrjali so glavno hipotezo: \
**Glavna hipoteza:** Vzorci samomorilskih misli so povezani z psihološkimi dejavniki (depresija, anksioznost in stres). 

in dodatne hipoteze: \
**Dodatne hipoteze:** Različni psihološki, socialno-demografski in telesni dejavniki vplivajo na intenzivnost samomorilskih misli; obstajajo razlike v vzorcih misli med skupinami z viskim in nizkim rizikom za samomor.\

Zanimal jih je vzorec samomorilskih misli, ki naj bi ga pojsanili z opisom depresije, anksioznosti in stresa, zdravstvenega stanje, preteklih samomorilskih poskusov, duševnih težav, časa od prve psihiatrične diagnoze ter uporabo zdravil.

# Populacija

Raziskava vsebuje kar nekaj predpostavk za vključitev ljudi v vzorec raziskave in sicer

- starejši so od 19 let,
- imajo pametni telefon,
- lahko nosijo napravo za aktigrafijo,
- govorijo in pišejo korejsko,
- so imeli samomorilske misli ali vedenje v zadnjem tednu,
- morajo razumeti namen raziskave,
- prostovoljno podati soglasje sodelovanja in 
- ne smejo sodelovati v drugih raziksavah.

Ocenili so, da potrebujejo vzorec velikosti vsaj 128 oseb oz. 150 oseb, ker so pričakovali izstope iz raziskave. Zaradi izvedbe študije med pandemijo COVID-19, je bilo težko zagotoviti zadostno število udeležencev. Na koncu so imeli 50 oseb starih od 19 do 58 let; razdeljeni so bili v dve skupini, visoko in nizko rizična skupina, v razmerju 80% in 20%. Razlika med skupinama je v samomorilskem vedenju. Iz raziksave, je zaradi različnih razlogov, izstopilo 5 oseb. Nobeden od izključenih oseb v času raziskave pa ni izstopil zaradi uspešnega samomora.

# Potek študije

Vsak od udeležencev je 3x na dan, vsak dan, cca 20 minut poročal o svojem razpoloženju, anksioznosti, stresu in samomorilskih misli. To je delal 28 dni. Ampak v študiji sva našla, da je povprečje 25,1 dni, torej niso vsi reševali vseh 28 dni; razpon od 15 do 28 dni. Zato je zanimivo, da od oseb, ki so izstopili, rezultatov niso upoštevali.\
Prav tako niso rešili vseh vprašalnikov, saj so v 76% dokončali anketo. 

Podatke so zbirali od maja 2021 do julija 2023. Konstantno pa v študiji poudarjajo, da rezultati niso posplošljivi, zaradi narave vzorca oseb.

Uporabili so kar nekaj statističnih metod. Glavno hipotezo, torej učinke trenutne depresije, anksioznosti in stresa na samomorilne misli so preučili z uporabo treh različnih panelnih mešanih linearnih regresijskih modelov (za posamezno skupino tveganja), v katere so bile vključene različne spremenljivke. \
Rezultati kažejo, da bi lahko daljinsko spremljanje in uporaba EMA izboljšala klinične prakse ter omogočila
bolj prilagojeno obravnavo bolnikov z visokim tveganjem za samomor.

# Zaključek

Raziskava sledi opisanemu protokolu, presenetil naju je podroben opis vseh metod dela, zbiranja podatkov in statističnih metod. V članku študije je tudi vedno jasno poudarjeno, da so določene stvari razložene in opisane v protokolu študije. Zato nisva imela večjih težav z razumevanjem strokovne terminologoje, kljub temu, da sva na tem podoročju popolnoma brez znanaja.

Zaradi opisa preteklih študij in ozadja študije, ter poudarka, da rezultati niso posplošljivi na celotno populacijo, naju je presenetila sama izvedba raziskave. 28 - dnevno sprejmlajne in ločitev na dve skupini naj bi sicer rešilo pomankljivosti preteklih raziskav, ampak zaradi poudarka o neposplošljivosti ne vididva dodane vrednosti. Poleg tega, tudi ločitev na dve skupini ne veva kako kaj doprineseta, saj je ena skupina izjemno majhna(n=10).

